version: "3.9"

name: remindly

networks:
  remindly-app-net:
    driver: bridge

x-postgres-healthcheck: &postgres-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 20
  start_period: 10s

services:
  postgres-remindly:
    restart: unless-stopped
    image: postgres:latest
    container_name: remindly-db
    environment:
      TZ: Europe/Tallinn
      POSTGRES_DB: remindlydb
      POSTGRES_USER: remindly
      POSTGRES_PASSWORD: remindly
    healthcheck: *postgres-healthcheck
    ports:
      - "54321:5432"
    networks:
      - remindly-app-net
    volumes:
      - ./src/main/resources/db/dev:/docker-entrypoint-initdb.d

  remindly:
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    container_name: remindly
    environment:
      TZ: Europe/Tallinn
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-remindly:5432/remindlydb?currentSchema=remindly
      SPRING_DATASOURCE_USERNAME: remindly
      SPRING_DATASOURCE_PASSWORD: remindly
      APP_EXTERNAL_BASE_URL: ${APP_EXTERNAL_BASE_URL}
      NTFY_SERVER_URL: ${NTFY_SERVER_URL}
      NTFY_ERRORS_TOPIC: ${NTFY_ERRORS_TOPIC}
      NTFY_ERRORS_TOPIC_ENABLED: ${NTFY_ERRORS_TOPIC_ENABLED}
      NTFY_GARBAGE_COLLECTION_TOPIC: ${NTFY_GARBAGE_COLLECTION_TOPIC}
      NTFY_GARBAGE_COLLECTION_TOPIC_ENABLED: ${NTFY_GARBAGE_COLLECTION_TOPIC_ENABLED}
      NTFY_ADHOC_TOPIC: ${NTFY_ADHOC_TOPIC}
      NTFY_ADHOC_TOPIC_ENABLED: ${NTFY_ADHOC_TOPIC_ENABLED}
    ports:
      - "9999:8080"
    depends_on:
      postgres-remindly:
        condition: service_healthy
    networks:
      - remindly-app-net