spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: remindly
  datasource:
    url: jdbc:postgresql://localhost:54321/remindlydb?currentSchema=remindly
    username: remindly
    password: remindly
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  liquibase:
    default-schema: liquibase
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  reminders:
    - name: errors
      topic: ${NTFY_ERRORS_TOPIC}
      enabled: true
    - name: garbage-collection
      topic: ${NTFY_GARBAGE_COLLECTION_TOPIC}
      enabled: true
    - name: adhoc
      topic: ${NTFY_ADHOC_TOPIC}
      enabled: true
