spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: remindly
  datasource:
    url: jdbc:postgresql://localhost:54321/remindlydb?currentSchema=remindly
    username: remindly
    password: remindly
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  liquibase:
    default-schema: liquibase
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  externalBaseUrl: ${APP_EXTERNAL_BASE_URL}
  ntfy-server: ${NTFY_SERVER_URL}
  reminders:
    - name: errors
      topic: ${NTFY_ERRORS_TOPIC}
      enabled: ${NTFY_ERRORS_TOPIC_ENABLED}
    - name: garbage-collection
      topic: ${NTFY_GARBAGE_COLLECTION_TOPIC}
      enabled: ${NTFY_GARBAGE_COLLECTION_TOPIC_ENABLED}
    - name: adhoc
      topic: ${NTFY_ADHOC_TOPIC}
      enabled: ${NTFY_ADHOC_TOPIC_ENABLED}
  gmail:
    credentials-file: ${GMAIL_CREDENTIALS_FILE}
    token-directory: ${GMAIL_TOKEN_DIRECTORY}
    sender: ${GMAIL_SENDER}
    auth-callback-url: ${GMAIL_AUTH_CALLBACK_BASE_URL}
